citusdata/the-process

circleci/images/extbuilder/files/bin/build-ext, circleci/images/extbuilder/files/sbin/install-extdeps, circleci/images/exttester/Dockerfile, circleci/images/exttester/files/sbin/install-testdeps
This PR adds postgres12 support for our test images. 
Normally we were using pg base image, however this causes some problems with pg12. pg12 base image has libcurl4 not libcurl3 apt source. Therefore when we install libcurl it installs libcurl4 not libcurl3. This gives an error in citus compilation. I have used the same base image that is used in https://github.com/citusdata/the-process/blob/master/circleci/images/extbuilder/Dockerfile#L2. This base image has libcurl3 not libcurl4.
`citusdata` repository is updated with `citus-bot`.
=> Add Postgres12 support

circleci/images/stylechecker/Dockerfile
Right now our ci/*.sh scripts need to use `sh` instead of `bash`. This is
annoying, since some useful things are not supported (non exhaustive list):
1. `set -o pipefail`
2. Some variable string replacement syntax things
=> Add bash to stylechecker Dockerfile

circleci/images/extbuilder/files/bin/build-ext
We decided not to install downgrade scripts by default. That's why we need to replace `make install` steps with `make install-all` to be able to test the downgrade scripts on CI.
See: https://github.com/citusdata/citus/pull/4004
=> Install downgrade scripts, if possible

circleci/images/citusupgradetester/files/sbin/install-extdeps, circleci/images/exttester/files/sbin/install-testdeps, circleci/images/failtester/files/sbin/install-testdeps, circleci/images/pgupgradetester/files/sbin/install-testdeps
As we are separating the builds for each pg major, we needed to add some
additional packages to some of the images to be able to pass configure
and run tests.
=> Update test images

circleci/images/exttester/Dockerfile, circleci/images/exttester/files/sbin/install-testdeps
For some tests in certain suites we use the `da_DK` locale. This patch adds them to our test containers.
While I was at it I have added the postgres bin dir to the path for easier scripting.
=> Add locales to test containers

circleci/images/citusupgradetester/files/etc/requirements.txt, circleci/images/failtester/files/etc/requirements.txt, circleci/images/failtester/files/sbin/install-testdeps, circleci/images/pgupgradetester/files/etc/requirements.txt
requirements.txt also exist for pgupgradetester and citusupgradetester images. We can update them but the updated packages are not used by those containers so it should be fine to not update them.
=> Failtester update requirement

circleci/images/Makefile
When we use latest tag for an image, it makes it harder to maintain old
branches that were depending on an old image, so it makes sense to have
a version that is more specific so that when we upgrade we can change
the tag and the old tag still exists.
=> Use 11-12-13 tag for pg upgrade tester

circleci/images/exttester/Dockerfile
To be able to run postgres' tap test framework we need to have the `IPC::Run` library for perl installed in our test container. Since this package is not directly installable from `apt` we install `cpanminus` that comes with/is an installer for perl modules.
Subsequently we install the required perl library.
=> add dependencies for running the postgres tap infrastructure

circleci/images/Makefile
We dropped pg 11 support hence we remove it from the images.
We should add more citus upgrade tester images and it should be done when we address this issue https://github.com/citusdata/citus/issues/4807
=> Update citus upgrade tester image

circleci/images/Makefile, circleci/images/exttester/Dockerfile
Beta versions are slightly differently tagged with characters (`~`) that are not allowed in docker tags.
These changes strip this character away at certain steps, however, the qualified version for pg14 beta3 will be `14~beta3` in the docker file.
=> Add CI images for pg14 beta3

circleci/images/citusupgradetester/Dockerfile, circleci/images/extbuilder/Dockerfile, circleci/images/exttester/Dockerfile, circleci/images/failtester/Dockerfile, circleci/images/pgupgradetester/Dockerfile
For postgres 13.4 there are 2 concurrent released versions:
- 13.4-1
- 13.4-4
The bash pipeline to infer the version to use had troubles parsing the versions
with more than 1 package per postgres minor version.
This PR changes the bash pipeline to correctly choose 1. For now we just take
the first one it finds with the use of `head -n1`.
=> Fix the installation of postgres when more then 1 release is available

circleci/images/Makefile
Postgres versions are updated to 12.9, 13.5 and 14.1 in Makefile. Additionally I parameterized PG_UPGRADE_TESTER to prevent duplicate version parameter
=> Updates postgres versions into latest

.github/workflows/build-test-images.yml, circleci/images/Makefile
Building images locally may be cumbersome since downloading and pushing takes too much time and resource even sometimes interrupted because of PC resource problems. This pipeline adds development image with suffix when current branch is not master, i.e. PR is still open for the development of images, adds a live image without suffix.
To make the development images parallel I added a sha suffix to make the parallel images have the same suffix
=> Adds docker image build & publish pipeline

circleci/images/Makefile
We also need to rollback some PG versions as the necessary development (https://github.com/citusdata/citus/pull/5505) is not still finished on Citus.
Sister PR: https://github.com/citusdata/citus/pull/5842
=> Remove PG12 from upgrade images

.github/workflows/build-test-images.yml
I needed to remove env parameter since env parameter could not be used in if clauses of  jobs
=> Fixes branch name and usage error in if clause

circleci/images/Makefile
In preparation of the postgres 15 release we need the first released beta version in CI to compile and test Citus against. This change adds the postgres 15~beta1 release to our testing matrix.
=> Add pg15 beta1 to our CI images

circleci/images/Makefile, circleci/images/citusupgradetester/Dockerfile, circleci/images/extbuilder/Dockerfile, circleci/images/exttester/Dockerfile, circleci/images/failtester/Dockerfile, circleci/images/pgupgradetester/Dockerfile
In the old images it would always ship with the latest version of libpq. This would have the downside that 
1. it was hard to reproduce the expected test outputs locally, since locally we switch libpq together with the postgres minor version
2. every time we would rebuild an image it could break the expected test output
To make it easier to add newer versions of postgres and/or rebuild images at a later point in time, as well as have passing tests locally we are changing CI in a way such that the libpq version is pinned to the same postgres minor version as the postgres server.
To make it easier to integrate this into our CI we need to remove the 15beta1 images again. Since that supresses the upgrade image to be made in a backwards compatible manner.
Upside is that after this patch it …
=> Stable libpq

circleci/images/Makefile
This PR is an alternative to #80 as it was not so easy to fix all the failures after we bump all PG minor versions to latest. Instead, we only add `PG15beta2` to the CI images, and keep the change minimal.
Closes: #80
=> Add 15beta2 CI images

circleci/images/failtester/Dockerfile
Setting up mitmproxy uses lsof and netstat. The were always used already
but not having lsof becomes a hard  failure with https://github.com/citusdata/citus/pull/6205
=> Add network tools to failtester image

circleci/images/exttester/Dockerfile
This adds `lcov` and `gdb` to our exttester images. `lcov` is needed to test
codeclimate for coverage and `gdb` is needed to show stacktraces of coredumps.
=> Add lcov and gdb

circleci/images/citusupgradetester/Dockerfile, circleci/images/exttester/Dockerfile, circleci/images/failtester/Dockerfile, circleci/images/pgupgradetester/Dockerfile
I added gdb and lcov previously, but added them to the layer that
compiles postgres instead of the layer that is used for testing...
This fixes that. 
It also adds a few more things that were necessary for codeclimate.
Such as git and the codeclimate binary.
Related PR that uses this can be found here: https://github.com/citusdata/citus/pull/6538
=> Prepare test images for coredumps and codeclimate

circleci/images/citusupgradetester/Dockerfile, circleci/images/extbuilder/Dockerfile, circleci/images/exttester/Dockerfile, circleci/images/failtester/Dockerfile, circleci/images/pgupgradetester/Dockerfile
Adds debug symbols into Postgres build to print useful stack traces from core files.
=> add debug symbols into postgres build

README.md, circleci/images/stylechecker/Dockerfile
When we add some scripts to run in CI, it is a nice idea to use long argument names. However, the busybox grep binary in our images do not support long argument names, and hence we install GNU grep.
Used in: https://github.com/citusdata/citus/pull/6661
=> Install grep in stylechecker image

circleci/images/stylechecker/Dockerfile, circleci/images/stylechecker/files/etc/requirements.txt
Needed to check Python formatting and linting from CI for https://github.com/citusdata/citus/pull/6700
Since some of these tools need a somewhat recent python version this also required an update of the alpine base image. And to make that in turn work, we need to install `uncrustify` from source (just like we recommend devs to do).
=> Install dev requirements in stylechecker

circleci/images/citusupgradetester/files/etc/requirements.txt, circleci/images/failtester/files/etc/requirements.txt, circleci/images/pgupgradetester/files/etc/requirements.txt, circleci/images/stylechecker/files/etc/requirements.txt
Dependabot was complaining about this issue, which I addressed on the
main repo in [#6710]. But to actually make it effective in CI we need to
update our images too.
[#6710]: https://github.com/citusdata/citus/pull/6710
=> Update vulnerable cryptography package

circleci/images/exttester/Dockerfile
https://github.com/citusdata/pgazure/pull/167 depends on a working Rust environment in a CI image.
We actually need some more tools and configurations in the images, but I intentionally did that in the project CI configs. Several benefits:
1. I do not make it considerably harder to locally build images.
2. The generated public docker images do not contain MS tools that are not really open.
3. We have a decreased attack surface considering we still do not access ADO in this repo.
=> Install Rust in exttester

circleci/images/exttester/Dockerfile
Added 3 library dependencies for CDC TAP tests:
libdbi-perl
libdbd-pg-perl
postgresql-${PG_MAJOR}-wal2json
This is needed for dependencies added for these PRs:
https://github.com/citusdata/citus/pull/6827
https://github.com/citusdata/citus/pull/6623
=> Add dependencies for CDC TAP tests in Perl

circleci/images/citusupgradetester/files/etc/requirements.txt, circleci/images/failtester/files/etc/requirements.txt, circleci/images/pgupgradetester/files/etc/requirements.txt, circleci/images/stylechecker/files/etc/requirements.txt
Mostly a new export of `pipenv requirements` exported from https://github.com/citusdata/citus/pull/7231
Once this PR lands we can merge the Citus PR after updating the image tags to the newly built images from `master` here.
=> Fix dependabot cryptography 41.0.4

circleci/images/exttester/Dockerfile
Wal2json PG16 package is now available.
Sister PR https://github.com/citusdata/citus/pull/7361
=> Wal2json pg16 package available

.github/workflows/build-test-images.yml, circleci/images/Makefile, circleci/images/citusupgradetester/Dockerfile, circleci/images/extbuilder/Dockerfile, circleci/images/exttester/Dockerfile, circleci/images/failtester/Dockerfile, circleci/images/pgupgradetester/Dockerfile, circleci/images/stylechecker/Dockerfile, circleci/images/stylechecker/files/etc/requirements.txt
The main motivation of this patch is to move the images to the github container registry. But as quite often the case, the images were not building, thus some changes needed to be made to get the images to build.
- Python construct package is bumped. There was a dependency failing to install, which succeeds on a newer version. This change is made by changing the version on the citus repo,  and re-export the requirements.txt
- pin the `postgresql-$PG_MAJOR` version to the same pgdg version. For pg16.2 new packages have been created. This happens once in a while and to counter that we already pin most of the postgres ecosystem packages to a specific pgdg version. Somehow `postgresql-...` wasn't part of the pinning, causing some errors during image builds.
The scripts used the old syntax of …
=> Move CI images to GHCR
